### ISSUE TITLE
"Calendar design" link is broken

### ISSUE THREAD

**Issue by Daenyth** [AlbeyAmakiir/tenpo#1]
It seems like the author of the reddit post deleted it.

Here's a backup: https://web.archive.org/web/20191125115251/https://www.reddit.com/r/tokipona/comments/dr378j/lunisolar_calendar_for_toki_pona_done/

<details>
<summary>Full post text</summary>
toki, jan ale o. It's me again! Yes, the podcast guy. The toki kala podcast will hopefully be airing later on today, however this post is about something else entirely! Im going to break this post into sections so you can skip over ones if you already know/dont want to read it all.

ABOUT CALENDARS Toki Pona has a lot of semantic basis in hunter-gatherer societies, so theres words like alasa but no root word for say, electricity. This also carries over to time. People, because we all live in the 21st century, live in worlds that have a lot of time measurement in them. Hours, minutes, seconds, milliseconds. We have a calendar that bases the year on the earth's orbit around the sun, and breaks that up into some months and days for us. The Gregorian calendar.

However, the Gregorian calendar is not the only one in existence. There are many calendars from essentially every culture, sometimes based on the moon (such as the Islamic calendar), and sometimes based on the sun (like our calendar). However, there are also these little things called lunisolar calendars, a truly magical creation, that track both the phases of the moon AND keep everything within the general realm of the solar year and the seasons.* The chinese, buddhist, vietnamese, hindu, babylonian, and hebrew calendars (to name a select few) are some examples of these. Every calendar system requires calculation, and theres no one way to do each.

So, where and how does this all tie into toki pona?

CURRENT TOKI PONA TIME Well, Toki Pona is a language used by humans in the 21st century, all of which have internet access. Thus, we are affected by the passing of the sun and moon in the sky (also affects how we sleep, what we do, what we see) as well as our position in the year based on a calendar, typically the Gregorian calendar. The language reflects this.

Problem is (back to the beginning of the post): Toki Pona wasn't made with these things in mind. In fact, it was made with them, to some degree, intentionally out of mind. A solar calendar is more about the day of the year and whatnot, cuz the sun is a much LONGER cycle to measure, but toki pona does NOT fit this system well. You tell me its "December 27, 2019" without using nimi sin and/or weird number systems that break the intentional lack of one. So we get things like, "tenpo mun" to mean 'month' and "tenpo esun" for week [not the only things youll see but (most) common ones]. But... the months of a solar calendar arent really moon cycles et cetera et cetera-- here's the problem.

The moon, on the other hand, is a smaller cycle that can be broken up into parts. It is easily visible in the sky every night. A lunar system fits toki pona quite well-- we simply observe the sky. Not really any math needed here and we can keep rough track of where we are. However, New Problem: The lunar cycles are not in line with the solar orbit. This means that a) seasons will fall completely out of sync from year to year and b) we now have an arbitrary, half-functioning amount of months in a 'year.'

The other big problem is this is that we have to cement compounds, which toki pona just doesn't do. Toki Pona words and phrases are super fluid and context based. But, if we say tenpo mun means month and have to use that arbitrarily on a system where it isn't even a real moon cycle, we're kinda pinning the language down and forcing it to fit this weird system.

Now, imagine a system where we are following the easily portion and describable phases of the moon, BUT we also get to keep our measurement consistent with seasons [AND STILL NO TRACKING DAY NUMBER OR EQUINOX DATE TO DO SO!] It also has fluid names for where we are that fit toki pona much better and freely to the speakers desire!

Welcome to the wonderful world of a simple lunisolar calendar. Something that, after some deliberation and a good amount of messing with, I have created for toki pona.

NASIN TENPO SIN So, I'm just going to jump into describing this system because this is already a super long post and I haven't even told sina ale about tenpo pan!

There are 12 months in a year, sometimes 13 with a mun namako. These months are based on lunar cycles. So, the beginning of a month is on the new moon, or mun len (sin). Again, this compound is open. Call it mun pimeja, if you wish.

The days in a month alternate between 29 and 30, the first month of the year being 29 days. Don't worry though, you dont need to keep track of day number like I said before. Alternating 29 and 30 automatically keeps the months in line with the ~29.5 day long lunar cycle.

The year begins in Spring: tenpo kasi. (Again, this makes most sense to me, but if u wanna call spring something else in context of conversation thats pona). I divided the year up into 4 seasons. While this isnt true of every climate, I think it is for a lot of people, and, if not, the beauty is it doesnt rly matter! Just use tenpo seli and tenpo lete with 6 months each if u want!

The year looks like this: mun open pi tenpo kasi mun awen pi tenpo kasi mun pini pi tenpo kasi mun open pi tenpo seli mun awen pi tenpo seli mun pini pi tenpo seli mun open pi tenpo pan... and on with this pattern until tenpo lete. After the final month of winter, the new year starts! ma li sike sin e suno a!!

BUT... there is an additional mun namako (13th month) that must be added every few years. I won't go into the math of all of this of course, but basically I've set it up on an 8 year cycle. The mun namako keeps the lunar year in line with the solar year, since they aren't naturally synced. We add a 30 Day mun namako at the end of the year when it is needed, and then repeat the normal year with tenpo kasi like always.

In an 8 year cycle, the extra month needs added every 2, 5, and 7 year. SO, we have a 354 day year 5/8 times and a 384 day year on those special years with a mun namako. You like your Canada Day in the summer dont you!? [p.s.- not a real canadian].

Okay, so how do we describe this extra mun namako in toki pona? It's actually much easier than it appears! Apart from the fact that you can easily just follow the calendar I make and not ever fret about adding an extra lunar cycle, I still will demonstrate how this can easily be done.

1- no namako. 2- namako. 3- no namako. 4- no namako. 5- namako. 6- no namako. 7- namako. 8- no namako.

This means, we can use wan and tu to measure years between mun namako. We count, starting at year 1 of the cycle: "wan, namako. wan, tu, namako. wan, namako. wan." It even makes a rhythmic little saying! wan namako wan tu namako wan namakao wan!! cha cha!

I started the calendar on the Spring Equinox of 2001. The year Sonja published toki pona to the world! That means 2019 is year 18 of the sike mun calendar. While year number doesnt rly matter, cuz we can just describe where we are in the moon phase and season, its something to have:)

Anyway.... Back to how we describe days. There is a new moon, first quarter moon, full moon, and third quarter moon in each month, all the way up to the next new moon which is day 1 of the next month. We can split these up into "weeks" if we must, but i dont rly see a need to do so.

New Moon: mun len (sin) First Quarter: mun kipisi open Full Moon: mun suno (sin) / mun suli (sin) Third Quarter: mun kipisi pini

(Thousandth time: phrasing is open) Theres also time mun kama (time between new moon and full moon) and mun tawa (time between full moon and next new moon). We can split these up even further into mun lili kama and mun suli kama, before and after the first quarter but between the full moon. And then mun suli tawa and mun lili tawa in reverse, before and after the third quarter moon but between full and next new moon.

So, thats how we describe more specifically the moon shape/day of the month were on. We can add X nanpa wan / X nanpa tu to get more specific and basically you can have a whole system of tracking the month, day of the month (moon phase), and season in the solar year all in toki pona without weird compounds, or extra numbers!

One other important thing: the next 'day' begins when the sun sets. So, sun sets- day 1. Sun sets again, next day. This way we dont need to have any kind of clock or weird time measurement like '12:00 am' for when our day starts. It also keeps it open to the moon phase and various time zones! Note: this isnt something unrealistic I just made up, many calendars base the next day not on a specific clock time but by the set/rise of the sun.

This fits toki pona's 'describing in context' well, too.

TENPO NI WOO! Got all that out of the way. Now, all that's left is to tell you where we are now and give you the coming calendars so you can start journaling, planning, and dividing your time all in toki pona without a struggle to fit another system.

When the sun sets today (it is currently 11:55 am for me, November 3), it will be the first quarter moon (mun kipisi open). Pretty convenient, eh? This is the 9th day of the month mun awen pi tenpo pan (second month of autumn). [Right now its the 8th day for me bc the sun hasnt set yet to start the 9th].

This month is 30 days long, and like I said they alternate 30 and 29. This means that December 25 will be the second day (suno nanpa tu) of mun open pi tenpo lete -- first month of winter.

The New Year (Year 19) falls on ~March 23 of the gregorian calendar. And Year 18 is the 3/8 year in the cycle. Meaning the next mun namako year is Year 20 (2021 of Gregorian).

PINI Please feel free to ask questions and use this calendar!!!! Toki Pona is growing up a a a.

Soon we'll get our own holidays (apart from the now Toki Pona New Year! and whatnot xD).

awen pona!!

*other lunisolar calendars may put more emphasis on the solar year than lunar, but it still tracks both.

</details>

**Comment by AlbeyAmakiir** [comment]
Thanks for the heads up. Looks like it was deleted because they deleted their account.

I've updated the README and wiki.
